import fs from "node:fs/promises";
import path from "node:path";
import data from "../src/data/products.json" with { type: "json" };

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "dist");
const esc = s => String(s ?? "").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const url = p => `https://www.champoauto.com${p}`;
const productUrl = (category, product) => `/products/${category.slug}/${product.sku.toLowerCase()}/`;
const googleMeasurementId = "G-7S6Z52Q2XQ";
const googleTag = `<script async src="https://www.googletagmanager.com/gtag/js?id=${googleMeasurementId}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${googleMeasurementId}');</script>`;
const googleTagManagerId = "GTM-TCTPFSLG";
const googleTagManagerHead = `<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)})(window,document,'script','dataLayer','${googleTagManagerId}');</script>`;
const googleTagManagerBody = `<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${googleTagManagerId}" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`;

await fs.rm(out,{recursive:true,force:true});
await fs.mkdir(out,{recursive:true});
await fs.cp(path.join(root,"images"),path.join(out,"images"),{recursive:true});
await fs.cp(path.join(root,"src","assets"),path.join(out,"assets"),{recursive:true});

const nav = `<div class="utility"><span>Automotive accessories manufacturer</span><span>OEM · ODM · Private Label</span></div><header class="site-header"><a class="brand" href="/" aria-label="CHAMPO home"><span>C</span>CHAMPO</a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav id="site-nav"><a href="/#products">Products</a><a href="/oem-odm/">OEM & ODM</a><a href="/quality-control/">Quality</a><a href="/about/">About</a><a href="/#contact">Contact</a></nav><a class="header-cta" href="/#contact">Request a quotation <span>→</span></a></header>`;
const footer = `<footer><div class="footer-grid"><div><a class="brand brand-light" href="/"><span>C</span>CHAMPO</a><p>Automotive accessories, made for brands that expect more.</p></div><div><b>Explore</b><a href="/#products">Products</a><a href="/oem-odm/">OEM & ODM</a><a href="/quality-control/">Quality Control</a><a href="/sustainability/">Sustainability</a><a href="/faq/">Buyer FAQ</a></div><div><b>Company</b><a href="/about/">About CHAMPO</a><a href="/#factory">Factory</a><a href="/#certifications">Certifications</a><a href="mailto:${data.site.email}">${data.site.email}</a><span>Taizhou, Zhejiang, China</span></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} CHAMPO. All rights reserved.</span><span>Built for better journeys.</span></div></footer>`;
const organizationSchema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:"CHAMPO",url:url("/"),email:data.site.email,address:{"@type":"PostalAddress",addressLocality:"Taizhou",addressRegion:"Zhejiang",addressCountry:"CN"},description:"OEM and ODM manufacturer of automotive organizers, pet protection products and vehicle tool bags."})}</script>`;
const layout = ({title,description,body,canonical="/",schema="",robots="index,follow,max-image-preview:large"}) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${googleTagManagerHead}${googleTag}<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${esc(robots)}"><link rel="canonical" href="${url(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="CHAMPO"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url(canonical)}"><meta property="og:image" content="${url('/assets/hero/fast-response.jpg')}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script>${organizationSchema}${schema}</head><body>${googleTagManagerBody}${nav}<main>${body}</main>${footer}</body></html>`;
const inquiry = (context={subject:"Product development"}) => {
  const productFields=context.sku?`<input type="hidden" name="sku" value="${esc(context.sku)}"><input type="hidden" name="product" value="${esc(context.name)}"><div class="inquiry-product"><span>Product selected</span><strong>${esc(context.name)}</strong><small>Item no. ${esc(context.sku)}</small></div>`:"";
  return `<section class="contact" id="contact"><div><p class="eyebrow light">REQUEST A QUOTATION</p><h2>${context.sku?"Tell us your buying requirements.":"Have a product in mind?"}</h2><p>Share the expected quantity, market and customization needs. Our team will reply with MOQ, sample options and an estimated lead time.</p></div><form action="https://formsubmit.co/${data.site.email}" method="POST" data-rfq-form><input type="hidden" name="_subject" value="CHAMPO website inquiry: ${esc(context.subject)}"><input type="hidden" name="_next" value="${url('/thank-you/')}">${productFields}<div class="form-row"><label>Name<input name="name" required autocomplete="name"></label><label>Work email<input name="email" type="email" required autocomplete="email"></label></div><div class="form-row"><label>Company<input name="company" required autocomplete="organization"></label><label>Estimated quantity<input name="quantity" placeholder="e.g. 500 pcs"></label></div><div class="form-row"><label>Target market<select name="target_market"><option value="">Select market</option><option>North America</option><option>Europe</option><option>United Kingdom</option><option>Australia / New Zealand</option><option>Middle East</option><option>Other</option></select></label><label>Expected delivery date<input name="delivery_date" type="date"></label></div><label>Customization required<select name="customization"><option value="">Select requirements</option><option>Logo / private label</option><option>Custom color or material</option><option>Retail packaging</option><option>Product structure or dimensions</option><option>Multiple requirements</option><option>No customization</option></select></label><label>Project details<textarea name="message" rows="4" required placeholder="Target price, packaging, testing or other requirements"></textarea></label><button type="submit">Send RFQ <span>↗</span></button><p class="form-note">We normally respond within one business day.</p></form></section>`;
};
const card = (c,p) => `<a class="product-card" href="${productUrl(c,p)}" data-name="${esc(`${p.name} ${p.sku}`.toLowerCase())}" data-sku="${esc(p.sku.toLowerCase())}" data-type="${esc(p.productType||"Other")}" data-material="${esc(p.materialGroup||"Other Materials")}"><div class="product-image"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"><span>View product ↗</span></div><div><p>${esc(c.name)} · ${esc(p.sku)}</p><h3>${esc(p.shortName||p.name)}</h3></div></a>`;
const filterBar = c => {
  const types=[...new Set(c.products.map(p=>p.productType||"Other"))].sort();
  const materials=[...new Set(c.products.map(p=>p.materialGroup||"Other Materials"))].sort();
  return `<section class="catalog-tools" aria-label="Product filters"><label class="catalog-search"><span>Search products</span><input type="search" data-filter-search placeholder="Search name or item number"></label><label><span>Product type</span><select data-filter-type><option value="">All product types</option>${types.map(v=>`<option>${esc(v)}</option>`).join("")}</select></label><label><span>Material</span><select data-filter-material><option value="">All materials</option>${materials.map(v=>`<option>${esc(v)}</option>`).join("")}</select></label><label><span>Sort by</span><select data-filter-sort><option value="default">Catalog order</option><option value="name">Product name</option><option value="sku">Item number</option></select></label><button type="button" data-filter-reset>Clear filters</button><p class="filter-count" aria-live="polite"><strong data-filter-count>${c.products.length}</strong> products shown</p></section>`;
};

const featured=data.categories.flatMap(c=>c.products.slice(0,2).map(p=>[c,p])).slice(0,8);
const categoryImages={
  "car-organizers":["/assets/categories/organizer.jpg"],
  "pet-car-protection":["/assets/categories/pet-cover.jpg"],
  "vehicle-tool-kits":["/assets/categories/tool-kit.jpg"]
};
const categoryTiles=data.categories.map((c,i)=>`<a class="category-tile tile-${i+1} images-${categoryImages[c.slug].length}" href="/products/${c.slug}/"><span class="tile-media">${categoryImages[c.slug].map((img,n)=>`<img src="${img}" alt="${esc(c.name)}${n?" alternative application":""}">`).join("")}</span><div><span>${String(i+1).padStart(2,"0")}</span><h3>${esc(c.name)}</h3><p>${c.products.length} products</p></div></a>`).join("");
const publishedProductCount=data.categories.reduce((count,category)=>count+category.products.length,0);
const homeBody=`<section class="hero-slider" aria-label="CHAMPO service advantages"><div class="hero-slides"><article class="hero-slide active"><div class="hero-copy"><p class="eyebrow">01 · FAST RESPONSE · TAIZHOU, CHINA</p><h1>Small orders.<br>Fast replenishment.</h1><p class="hero-lede">Start with practical quantities, respond to market demand quickly and repeat successful products with less inventory pressure.</p><div class="hero-actions"><a class="button dark" href="#contact">Request a quotation</a><a class="text-link" href="#products">View product range →</a></div></div><div class="hero-visual"><img src="/assets/hero/fast-response.jpg" alt="Pet cargo liner in use"><div class="floating-note"><b>Lower-risk trial orders</b><span>Responsive repeat production</span></div></div></article><article class="hero-slide"><div class="hero-copy"><p class="eyebrow">02 · CUSTOM DEVELOPMENT</p><h2>Developed around<br>your market.</h2><p class="hero-lede">Adapt materials, structure, dimensions, colors, branding and packaging to create a product that fits your customer and price point.</p><div class="hero-actions"><a class="button dark" href="#contact">Discuss customization</a><a class="text-link" href="#capabilities">Our capabilities →</a></div></div><div class="hero-visual"><img src="/assets/hero/custom-development.jpg" alt="Custom car trunk organizer"><div class="floating-note"><b>OEM / ODM development</b><span>Product and packaging options</span></div></div></article><article class="hero-slide"><div class="hero-copy"><p class="eyebrow">03 · DELIVERY & SUPPORT</p><h2>On-time delivery.<br>Support that lasts.</h2><p class="hero-lede">Clear production updates, quality checkpoints and responsive after-sales support keep every order moving with confidence.</p><div class="hero-actions"><a class="button dark" href="#contact">Talk to our team</a><a class="text-link" href="#process">How we work →</a></div></div><div class="hero-visual"><img src="/assets/hero/delivery-support.jpg" alt="Vehicle tool bag"><div class="floating-note"><b>Reliable order follow-through</b><span>After-sales response</span></div></div></article></div><div class="slider-controls"><div class="slider-dots"><button class="active" aria-label="Show fast response slide">01</button><button aria-label="Show custom development slide">02</button><button aria-label="Show delivery and support slide">03</button></div><div class="slider-arrows"><button class="slider-prev" aria-label="Previous slide">←</button><button class="slider-next" aria-label="Next slide">→</button></div></div></section><section class="hero-stats"><div><strong>3</strong><span>focused automotive product lines</span></div><div><strong>${publishedProductCount}</strong><span>verified catalog products</span></div><div><strong>OEM</strong><span>materials, colors, logo and packaging</span></div></section>
<section class="category-section" id="products"><div class="section-head"><div><p class="eyebrow">WHAT WE MAKE</p><h2>Products that earn<br>their place in the car.</h2></div><p>Purposeful materials, practical construction and flexible customization across a focused automotive range.</p></div><div class="category-grid">${categoryTiles}</div></section>
<section class="manifesto"><p class="eyebrow light">A PRACTICAL SUPPLY PARTNER</p><p>Start smaller. Adapt faster. Reorder with confidence.</p><div class="manifesto-grid"><span>Lower-risk trial orders</span><span>Rapid sample development</span><span>Flexible private labeling</span><span>Responsive repeat production</span></div></section>
<section class="capabilities" id="capabilities"><div class="capability-image"><img src="${data.categories[0].products[4]?.image || data.categories[0].products[0].image}" alt="Automotive accessory detail" loading="lazy"></div><div><p class="eyebrow">ABOUT CHAMPO</p><h2>A responsive manufacturing partner for growing programs.</h2><p class="company-copy">We focus on fabric-based automotive accessories and work closely with customers who need practical quantities, quick product iterations and reliable replenishment. Instead of forcing every project into a fixed catalog, we adapt materials, construction, colors, branding and packaging to suit the target market.</p><div class="compliance-badges"><div><strong>BSCI</strong><span>amfori social audit completed</span></div><div><strong>GRS</strong><span>Global Recycled Standard V4.0</span></div><div><strong>ISO<br>9001</strong><span>Quality management · ISO 9001:2015</span></div></div><div class="accordion"><details open><summary>01 · Small-order flexibility</summary><p>Lower-risk trial orders help buyers test new products and markets before scaling.</p></details><details><summary>02 · Fast response & replenishment</summary><p>Direct communication and focused product lines support quicker sampling and repeat orders.</p></details><details><summary>03 · Product customization</summary><p>Material, dimensions, functional details and colorways can be developed around your brief.</p></details><details><summary>04 · Branding & packaging</summary><p>Custom logo, labels, inserts and retail-ready packaging for private-label programs.</p></details></div></div></section>
<section class="certifications" id="certifications"><div class="section-head"><div><p class="eyebrow">CERTIFICATIONS & COMPLIANCE</p><h2>Documents buyers<br>can verify.</h2></div><p>Review the issued documents, certification scope and stated validity periods before beginning supplier qualification.</p></div><div class="certificate-grid"><article class="certificate-card"><a class="certificate-preview" href="/assets/certificates/champo-iso-9001.pdf" target="_blank" rel="noopener"><img src="/assets/certificates/champo-iso-9001-preview.png" alt="ISO 9001:2015 certificate preview" loading="lazy"></a><div><span class="certificate-status active">Valid</span><p>QUALITY MANAGEMENT</p><h3>ISO 9001:2015</h3><dl><div><dt>Registration</dt><dd>25025Q12947R0S</dd></div><div><dt>Scope</dt><dd>Production of luggage and bags</dd></div><div><dt>Valid until</dt><dd>14 Sep 2028</dd></div></dl><a href="/assets/certificates/champo-iso-9001.pdf" target="_blank" rel="noopener">View certificate PDF →</a></div></article><article class="certificate-card"><a class="certificate-preview" href="/assets/certificates/champo-grs.pdf" target="_blank" rel="noopener"><img src="/assets/certificates/champo-grs-preview.png" alt="Global Recycled Standard certificate preview" loading="lazy"></a><div><span class="certificate-status expiring">Renewal in progress</span><p>RECYCLED MATERIALS</p><h3>GRS Version 4.0</h3><dl><div><dt>Certificate</dt><dd>SGC-GRC04426-GRS-2025-09</dd></div><div><dt>Scope</dt><dd>Home textiles & carried accessories</dd></div><div><dt>Valid until</dt><dd>07 Oct 2026</dd></div><div><dt>Renewal</dt><dd>Updated certificate expected Sep 2026</dd></div></dl><a href="/assets/certificates/champo-grs.pdf" target="_blank" rel="noopener">View current certificate →</a></div></article><article class="certificate-card"><a class="certificate-preview" href="/assets/certificates/champo-bsci.pdf" target="_blank" rel="noopener"><img src="/assets/certificates/champo-bsci-preview.png" alt="amfori BSCI monitoring report preview" loading="lazy"></a><div><span class="certificate-status active">Valid</span><p>SOCIAL COMPLIANCE AUDIT</p><h3>amfori BSCI</h3><dl><div><dt>Monitoring ID</dt><dd>26-0426080</dd></div><div><dt>Overall rating</dt><dd>C</dd></div><div><dt>Valid until</dt><dd>14 Aug 2027</dd></div></dl><a href="/assets/certificates/champo-bsci.pdf" target="_blank" rel="noopener">View monitoring report →</a></div></article></div><p class="certificate-note">Certificate status shown as of September 2026. GRS renewal is in progress and the updated certificate will be posted after issue. Product claims remain subject to valid scope and transaction documentation.</p></section>
<section class="factory" id="factory"><div class="section-head"><div><p class="eyebrow">INSIDE OUR FACTORY</p><h2>A real production team,<br>visible at every step.</h2></div><p>From sampling and sewing to in-process handling and finished-goods staging, your program is supported by an operating factory in Taizhou.</p></div><div class="factory-grid"><figure class="factory-main"><img src="/assets/factory/workshop.jpg" alt="Wide view of CHAMPO's active sewing workshop" loading="lazy"><figcaption><span>01</span><b>Production workshop</b><small>Active sewing lines and organized work zones</small></figcaption></figure><figure><img src="/assets/factory/production-floor.jpg" alt="Operators producing automotive textile accessories" loading="lazy"><figcaption><span>02</span><b>Sewing & assembly</b><small>Skilled operators working on current production</small></figcaption></figure><figure><img src="/assets/factory/sample-room.jpg" alt="Automotive accessory sample room" loading="lazy"><figcaption><span>03</span><b>Sample room</b><small>Product references for development and review</small></figcaption></figure><figure class="factory-wide"><img src="/assets/factory/finished-goods-anonymized.png" alt="Finished goods staging area inside the factory" loading="lazy"><figcaption><span>04</span><b>Finished-goods staging</b><small>Customer markings removed for confidentiality</small></figcaption></figure></div><div class="factory-facts"><div><span>Facility area</span><strong>3,000 m²</strong></div><div><span>Employees</span><strong>60</strong></div><div><span>Sewing machines</span><strong>80</strong></div><div><span>Sample makers</span><strong>3</strong></div><div><span>Typical sample lead time</span><strong>7 days</strong></div><div><span>Peak-season lead time</span><strong>About 30 days</strong></div></div><div class="production-flow"><span>MAIN PRODUCTION PROCESSES</span><p>Cutting · Sewing · Embroidery · Screen printing · Bartacking · Quality inspection · Snap fastening · Packing</p></div><p class="factory-note">Actual CHAMPO facility photography. Customer-identifying carton marks have been digitally removed; the production environment has not been replaced or fabricated.</p></section>
<section class="experience" id="experience"><div class="section-head"><div><p class="eyebrow">PROGRAM EXPERIENCE</p><h2>Built for different<br>routes to market.</h2></div><p>Working through established export partners, we have supported product programs supplied into major North American retail channels.</p></div><div class="case-grid"><article><span>01</span><p>Warehouse retail</p><h3>Pet travel protection program</h3><p>Material adaptation, reinforced construction, retail packaging and volume production for a North American warehouse retail channel.</p></article><article><span>02</span><p>Automotive retail</p><h3>Vehicle tool storage program</h3><p>Private-label tool bags developed around assortment, packing and repeat-delivery requirements for an automotive retail channel.</p></article><article><span>03</span><p>Import & distribution</p><h3>Car organization program</h3><p>Flexible trunk organizer development for importers testing multiple styles, colors and market price points.</p></article></div><div class="capacity-panel"><div><p class="eyebrow light">DAILY PRODUCTION CAPACITY</p><h2>From trial orders to repeat volume.</h2><p>Focused production lines allow us to respond to different order sizes and replenishment schedules.</p></div><dl><div><dt>Car organizers</dt><dd><strong>1,000</strong><span>pcs / day</span></dd></div><div><dt>Pet protection</dt><dd><strong>1,000</strong><span>sets / day</span></dd></div><div><dt>Vehicle tool bags</dt><dd><strong>3,000</strong><span>pcs / day</span></dd></div></dl></div><p class="disclosure">Program descriptions are anonymized. Products were supplied through export partners; no direct commercial relationship with downstream retailers is implied.</p></section>
<section class="process" id="process"><div class="section-head"><div><p class="eyebrow">HOW WE WORK</p><h2>A clear route from<br>idea to delivery.</h2></div></div><ol><li><span>01</span><b>Share the brief</b><p>Product, target price, quantity and market.</p></li><li><span>02</span><b>Confirm the solution</b><p>Materials, details, sample and quotation.</p></li><li><span>03</span><b>Make & inspect</b><p>Production with quality checkpoints.</p></li><li><span>04</span><b>Pack & ship</b><p>Final inspection and export coordination.</p></li></ol></section>${inquiry()}`;
await fs.writeFile(path.join(out,"index.html"),layout({title:"CHAMPO | Automotive Accessories Manufacturer",description:"OEM and ODM automotive organizers, pet seat covers, cargo liners and car protection products.",body:homeBody,canonical:"/"}));

const infoPages=[
  {slug:"about",title:"About CHAMPO | Automotive Accessories Manufacturer",description:"Meet CHAMPO, a Taizhou manufacturer focused on automotive organizers, pet protection products, vehicle tool bags and flexible OEM programs.",body:`<section class="info-hero"><p class="eyebrow">ABOUT CHAMPO</p><h1>A focused automotive accessories manufacturer.</h1><p>CHAMPO develops and manufactures fabric-based automotive organizers, pet travel protection products and vehicle tool bags in Taizhou, Zhejiang, China.</p></section><section class="info-grid"><article><span>01</span><h2>Built for responsive programs</h2><p>We support practical trial quantities, rapid product iteration and repeat production for importers, distributors and private-label programs.</p></article><article><span>02</span><h2>Operating factory</h2><p>Our 3,000 m² facility has 60 employees, 80 sewing machines and three dedicated sample makers.</p></article><article><span>03</span><h2>Production capability</h2><p>Core processes include cutting, sewing, embroidery, screen printing, bartacking, inspection, snap fastening and packing.</p></article></section><section class="info-cta"><h2>Review our factory and certifications.</h2><div><a class="button dark" href="/#factory">View factory</a><a class="text-link" href="/#certifications">View certifications →</a></div></section>`},
  {slug:"oem-odm",title:"Automotive Accessories OEM & ODM | CHAMPO",description:"OEM and ODM development for automotive organizers, pet seat covers, cargo liners and tool bags with custom materials, colors, logos and packaging.",body:`<section class="info-hero"><p class="eyebrow">OEM & ODM</p><h1>Developed around your market.</h1><p>Start from an existing product or share a new brief. We adapt materials, dimensions, functional details, colors, branding and packaging to suit your customer and target price.</p></section><section class="process info-process"><ol><li><span>01</span><b>Product brief</b><p>Application, target price, quantity and market requirements.</p></li><li><span>02</span><b>Material & construction</b><p>Fabric, support board, padding, hardware and functional details.</p></li><li><span>03</span><b>Brand presentation</b><p>Logo method, labels, colorways, inserts and retail packaging.</p></li><li><span>04</span><b>Sample & production</b><p>Typical samples in seven days, followed by confirmed production planning.</p></li></ol></section>${inquiry({subject:"OEM / ODM development"})}`},
  {slug:"quality-control",title:"Automotive Accessories Quality Control | CHAMPO",description:"CHAMPO quality-control workflow covering material handling, cutting, sewing, bartacking, in-process checks, final inspection and packing.",body:`<section class="info-hero"><p class="eyebrow">QUALITY CONTROL</p><h1>Checks built into the production flow.</h1><p>Quality requirements are confirmed with the approved sample and carried through material preparation, production, finishing and packing.</p></section><section class="info-grid quality-steps"><article><span>01</span><h2>Pre-production confirmation</h2><p>Confirm specifications, materials, colors, logo placement, packaging and the approved sample.</p></article><article><span>02</span><h2>In-process inspection</h2><p>Monitor cutting, sewing, embroidery, screen printing, bartacking and snap fastening against confirmed requirements.</p></article><article><span>03</span><h2>Final inspection & packing</h2><p>Check workmanship, quantity and packing presentation before finished goods are staged for shipment.</p></article></section><section class="info-cta"><h2>Need a specific inspection plan?</h2><p>Include your AQL, testing or retailer requirements in the RFQ.</p><a class="button dark" href="/#contact">Discuss quality requirements</a></section>`},
  {slug:"sustainability",title:"Recycled Materials and Compliance | CHAMPO",description:"Information about CHAMPO GRS scope, recycled-material product development and documentation for supplier qualification.",body:`<section class="info-hero"><p class="eyebrow">SUSTAINABILITY & COMPLIANCE</p><h1>Recycled-material options with documented scope.</h1><p>CHAMPO can discuss recycled-material options for suitable product programs. Claims depend on valid certification scope and transaction documentation for the goods supplied.</p></section><section class="info-grid"><article><span>GRS</span><h2>Current certificate</h2><p>The current Global Recycled Standard Version 4.0 certificate is valid until 07 October 2026.</p></article><article><span>2026</span><h2>Renewal in progress</h2><p>An updated certificate is expected in September 2026 and will be posted after issue.</p></article><article><span>TC</span><h2>Product-level documentation</h2><p>Certification of a facility does not automatically certify every order. Product claims remain subject to applicable scope and transaction certificates.</p></article></section><section class="info-cta"><h2>Review the issued document.</h2><a class="button dark" href="/assets/certificates/champo-grs.pdf" target="_blank" rel="noopener">View current GRS certificate</a></section>`},
];
for(const page of infoPages){const dir=path.join(out,page.slug);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"index.html"),layout({title:page.title,description:page.description,body:page.body,canonical:`/${page.slug}/`}))}

const faqItems=[
  ["What products does CHAMPO manufacture?","We focus on car organizers, automotive pet protection products, cargo liners and vehicle tool bags."],
  ["Can I start with a trial order?","Yes. Practical trial quantities are available, while the final MOQ depends on material, construction, branding and packaging."],
  ["How long does sampling take?","A typical sample takes about seven days after specifications and materials are confirmed."],
  ["What is the usual production lead time?","Peak-season production lead time is approximately 30 days. The confirmed schedule depends on quantity, material availability and customization."],
  ["What can be customized?","Materials, dimensions, functional details, colors, logo application, labels, inserts and retail packaging can be developed for OEM and private-label programs."],
  ["What certifications are available?","Current ISO 9001, GRS and amfori BSCI documents are available on the website for buyer review. Scope and validity should be checked for each program."],
];
const faqSchema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqItems.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))})}</script>`;
const faqBody=`<section class="info-hero"><p class="eyebrow">BUYER FAQ</p><h1>Common sourcing questions.</h1><p>Key information for buyers evaluating a trial order, custom development or repeat production.</p></section><section class="faq-list">${faqItems.map(([q,a],i)=>`<details ${i===0?"open":""}><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join("")}</section>${inquiry({subject:"Buyer FAQ inquiry"})}`;
await fs.mkdir(path.join(out,"faq"),{recursive:true});await fs.writeFile(path.join(out,"faq","index.html"),layout({title:"Automotive Accessories Buyer FAQ | CHAMPO",description:"Answers about CHAMPO products, trial-order MOQ, samples, production lead time, OEM customization and certifications.",body:faqBody,canonical:"/faq/",schema:faqSchema}));
const thankYouBody=`<section class="info-hero"><p class="eyebrow">RFQ RECEIVED</p><h1>Thank you for contacting CHAMPO.</h1><p>Your requirements have been sent to our team. We normally reply within one business day with the next steps for quotation, sampling or custom development.</p><div class="hero-actions"><a class="button dark" href="/#products">Continue browsing products</a><a class="text-link" href="/oem-odm/">Review OEM & ODM options →</a></div></section><script>if(sessionStorage.getItem('champo_rfq_pending')==='1'){sessionStorage.removeItem('champo_rfq_pending');window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'generate_lead',form_name:'rfq'});if(typeof gtag==='function')gtag('event','generate_lead',{method:'website_rfq'})}</script>`;
await fs.mkdir(path.join(out,"thank-you"),{recursive:true});await fs.writeFile(path.join(out,"thank-you","index.html"),layout({title:"Thank You | CHAMPO",description:"Your request has been sent to CHAMPO.",body:thankYouBody,canonical:"/thank-you/",robots:"noindex,nofollow"}));

const legacySourceSlug={"Trunk Organizers":"storage-box","Seat Organizers":"seat-hanging-bag","Pet Seat Covers":"pet-seat-cover","Cargo Liners":"trunk-mat","Tool Bags":"tool-kit"};
for(const c of data.categories){
  const dir=path.join(out,"products",c.slug); await fs.mkdir(dir,{recursive:true});
  const body=`<section class="page-hero"><p class="eyebrow">PRODUCT COLLECTION</p><h1>${esc(c.name)}</h1><p>${esc(c.intro)}</p><span>${c.products.length} products</span></section>${filterBar(c)}<section class="catalog-grid" data-product-grid>${c.products.map(p=>card(c,p)).join("")}<p class="filter-empty" data-filter-empty hidden>No matching products. Try clearing one of the filters.</p></section>${inquiry({subject:c.name})}`;
  const categorySchema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage",name:c.name,description:c.intro,url:url(`/products/${c.slug}/`),mainEntity:{"@type":"ItemList",numberOfItems:c.products.length,itemListElement:c.products.map((p,i)=>({"@type":"ListItem",position:i+1,url:url(productUrl(c,p)),name:p.name}))}})}</script>`;
  await fs.writeFile(path.join(dir,"index.html"),layout({title:`${c.name} | CHAMPO`,description:c.intro,body,canonical:`/products/${c.slug}/`,schema:categorySchema}));
  for(const [productIndex,p] of c.products.entries()){
    const pdir=path.join(dir,p.sku.toLowerCase()); await fs.mkdir(pdir,{recursive:true});
    const facts=[["Item no.",p.sku],["Material",p.material],["Product size",p.dimension],["Product weight",p.weight],["Carton size",p.cartonDimension],["Quantity / carton",p.cartonQuantity],["Carton net weight",p.cartonNetWeight],["Carton gross weight",p.cartonGrossWeight],["MOQ",p.moq||"Ask us"],["Colors",p.colors.join(", ")||"Custom options"]].filter(x=>x[1]);
    const gallery=[p.image,...p.gallery].slice(0,4).map((img,i)=>`<img src="${img}" alt="${esc(p.name)}${i?` detail ${i}`:""}" ${i?"loading=\"lazy\"":""}>`).join("");
    const seoDescription=`${p.shortName||p.name} ${p.sku} in ${p.material||"custom materials"}. OEM, private-label and packaging options from CHAMPO.`;
    const schema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"Product",name:p.name,sku:p.sku,image:[url(p.image),...p.gallery.map(url)],brand:{"@type":"Brand",name:"CHAMPO"},manufacturer:{"@type":"Organization",name:"CHAMPO"},category:c.name,description:seoDescription})}</script><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:url("/")},{"@type":"ListItem",position:2,name:c.name,item:url(`/products/${c.slug}/`)},{"@type":"ListItem",position:3,name:p.name,item:url(productUrl(c,p))}]})}</script>`;
    const previous=c.products[(productIndex-1+c.products.length)%c.products.length];
    const next=c.products[(productIndex+1)%c.products.length];
    const related=c.products.filter(item=>item.sku!==p.sku&&item.productType===p.productType).slice(0,3);
    const sameMaterial=c.products.filter(item=>item.sku!==p.sku&&item.materialGroup===p.materialGroup).slice(0,3);
    const relatedProducts=(related.length?related:sameMaterial.length?sameMaterial:c.products.filter(item=>item.sku!==p.sku).slice(0,3));
    const productNav=`<nav class="product-nav" aria-label="Product navigation"><a href="${productUrl(c,previous)}"><span>Previous product</span><strong>${esc(previous.shortName||previous.name)}</strong><small>${esc(previous.sku)}</small></a><a href="/products/${c.slug}/"><span>Back to collection</span><strong>View all ${esc(c.name)}</strong></a><a href="${productUrl(c,next)}"><span>Next product</span><strong>${esc(next.shortName||next.name)}</strong><small>${esc(next.sku)}</small></a></nav>`;
    const relatedSection=`<section class="related-products"><div class="section-head compact"><div><p class="eyebrow">RELATED PRODUCTS</p><h2>More options for your program.</h2></div></div><div class="catalog-grid">${relatedProducts.map(item=>card(c,item)).join("")}</div></section>`;
    const pbody=`<nav class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/products/${c.slug}/">${esc(c.name)}</a><span>/</span><b>${esc(p.sku)}</b></nav><section class="product-detail"><div class="gallery">${gallery}</div><div class="product-info"><p class="eyebrow">${esc(c.name)} · ${esc(p.sku)}</p><h1>${esc(p.shortName||p.name)}</h1><p class="product-lede">${esc(p.description||c.intro)}</p><dl>${facts.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl><div class="product-actions"><a class="button dark wide" href="#contact">Request quote</a><button class="spec-button" type="button" data-print-spec>Print / Save specification PDF</button></div><p class="microcopy">Logo, color and packaging customization available.</p></div></section>${productNav}${relatedSection}${inquiry({subject:`${p.sku} / ${p.name}`,sku:p.sku,name:p.shortName||p.name})}`;
    await fs.writeFile(path.join(pdir,"index.html"),layout({title:`${p.name} | CHAMPO`,description:seoDescription,body:pbody,canonical:productUrl(c,p),schema}));
    const oldSlug=legacySourceSlug[p.sourceCategory];
    if(oldSlug){const oldDir=path.join(out,"products",oldSlug,p.sku.toLowerCase());await fs.mkdir(oldDir,{recursive:true});const target=productUrl(c,p);await fs.writeFile(path.join(oldDir,"index.html"),`<!doctype html><meta charset="utf-8"><link rel="canonical" href="${url(target)}"><meta http-equiv="refresh" content="0;url=${target}"><title>Moved | CHAMPO</title><a href="${target}">View this product</a>`)}
  }
}
const legacyCategories={"storage-box":"car-organizers","seat-hanging-bag":"car-organizers","pet-seat-cover":"pet-car-protection","trunk-mat":"pet-car-protection","tool-kit":"vehicle-tool-kits"};
for(const [oldSlug,newSlug] of Object.entries(legacyCategories)){const d=path.join(out,"products",oldSlug);await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"index.html"),`<!doctype html><meta charset="utf-8"><link rel="canonical" href="${url(`/products/${newSlug}/`)}"><meta http-equiv="refresh" content="0;url=/products/${newSlug}/"><title>Moved | CHAMPO</title><a href="/products/${newSlug}/">View the current collection</a>`)}
const allProducts=data.categories.flatMap(c=>c.products.map(p=>({sku:p.sku,name:p.name,category:c.name,url:productUrl(c,p),image:p.image}))); 
await fs.writeFile(path.join(out,"products.json"),JSON.stringify(allProducts,null,2));
await fs.writeFile(path.join(out,"robots.txt"),`User-agent: *\nAllow: /\nSitemap: ${url('/sitemap.xml')}\nHost: www.champoauto.com\n`);
await fs.writeFile(path.join(out,"CNAME"),"www.champoauto.com\n");
await fs.writeFile(path.join(out,".nojekyll"),"");
const paths=["/",...infoPages.map(page=>`/${page.slug}/`),"/faq/",...data.categories.map(c=>`/products/${c.slug}/`),...data.categories.flatMap(c=>c.products.map(p=>productUrl(c,p)))];
await fs.writeFile(path.join(out,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${url(p)}</loc><lastmod>2026-09-10</lastmod></url>`).join("")}</urlset>`);
console.log(`Built ${paths.length} pages in ${out}`);
