import fs from "node:fs/promises";
import path from "node:path";
import data from "../src/data/products.json" with { type: "json" };

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "dist");
const esc = s => String(s ?? "").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const url = p => `https://www.champoauto.com${p}`;
const productUrl = (category, product) => `/products/${category.slug}/${product.sku.toLowerCase()}/`;

await fs.rm(out,{recursive:true,force:true});
await fs.mkdir(out,{recursive:true});
await fs.cp(path.join(root,"images"),path.join(out,"images"),{recursive:true});
await fs.cp(path.join(root,"src","assets"),path.join(out,"assets"),{recursive:true});

const nav = `<div class="utility"><span>Automotive accessories manufacturer</span><span>OEM · ODM · Private Label</span></div><header class="site-header"><a class="brand" href="/" aria-label="CHAMPO home"><span>C</span>CHAMPO</a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav id="site-nav"><a href="/#products">Products</a><a href="/#capabilities">Manufacturing</a><a href="/#process">How we work</a><a href="/#contact">Contact</a></nav><a class="header-cta" href="/#contact">Request a quotation <span>→</span></a></header>`;
const footer = `<footer><div class="footer-grid"><div><a class="brand brand-light" href="/"><span>C</span>CHAMPO</a><p>Automotive accessories, made for brands that expect more.</p></div><div><b>Explore</b><a href="/#products">Products</a><a href="/#capabilities">OEM & ODM</a><a href="/#contact">Contact</a></div><div><b>Get in touch</b><a href="mailto:${data.site.email}">${data.site.email}</a><span>Ningbo, Zhejiang, China</span></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} CHAMPO. All rights reserved.</span><span>Built for better journeys.</span></div></footer>`;
const layout = ({title,description,body,canonical="/",schema=""}) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url(canonical)}"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script>${schema}</head><body>${nav}<main>${body}</main>${footer}</body></html>`;
const inquiry = (subject="Product development") => `<section class="contact" id="contact"><div><p class="eyebrow light">LET'S BUILD SOMETHING USEFUL</p><h2>Have a product in mind?</h2><p>Tell us what you need. Our team will respond with options for materials, customization, MOQ and lead time.</p></div><form action="https://formsubmit.co/${data.site.email}" method="POST"><input type="hidden" name="_subject" value="CHAMPO website inquiry: ${esc(subject)}"><div class="form-row"><label>Name<input name="name" required autocomplete="name"></label><label>Work email<input name="email" type="email" required autocomplete="email"></label></div><label>Company<input name="company" autocomplete="organization"></label><label>What are you looking for?<textarea name="message" rows="4" required></textarea></label><button type="submit">Send inquiry <span>↗</span></button></form></section>`;
const card = (c,p) => `<a class="product-card" href="${productUrl(c,p)}"><div class="product-image"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"><span>View product ↗</span></div><div><p>${esc(c.name)}</p><h3>${esc(p.sku)}</h3></div></a>`;

const featured=data.categories.flatMap(c=>c.products.slice(0,2).map(p=>[c,p])).slice(0,8);
const categoryImages={
  "car-organizers":["/assets/categories/organizer.jpg"],
  "pet-car-protection":["/assets/categories/pet-cover.jpg"],
  "vehicle-tool-kits":["/assets/categories/tool-kit.jpg"]
};
const categoryTiles=data.categories.map((c,i)=>`<a class="category-tile tile-${i+1} images-${categoryImages[c.slug].length}" href="/products/${c.slug}/"><span class="tile-media">${categoryImages[c.slug].map((img,n)=>`<img src="${img}" alt="${esc(c.name)}${n?" alternative application":""}">`).join("")}</span><div><span>${String(i+1).padStart(2,"0")}</span><h3>${esc(c.name)}</h3><p>${c.products.length} products</p></div></a>`).join("");
const homeBody=`<section class="hero-slider" aria-label="CHAMPO service advantages"><div class="hero-slides"><article class="hero-slide active"><div class="hero-copy"><p class="eyebrow">01 · FAST RESPONSE</p><h1>Small orders.<br>Fast replenishment.</h1><p class="hero-lede">Start with practical quantities, respond to market demand quickly and repeat successful products with less inventory pressure.</p><div class="hero-actions"><a class="button dark" href="#contact">Request a quotation</a><a class="text-link" href="#products">View product range →</a></div></div><div class="hero-visual"><img src="/assets/hero/fast-response.jpg" alt="Pet cargo liner in use"><div class="floating-note"><b>Lower-risk trial orders</b><span>Responsive repeat production</span></div></div></article><article class="hero-slide"><div class="hero-copy"><p class="eyebrow">02 · CUSTOM DEVELOPMENT</p><h1>Developed around<br>your market.</h1><p class="hero-lede">Adapt materials, structure, dimensions, colors, branding and packaging to create a product that fits your customer and price point.</p><div class="hero-actions"><a class="button dark" href="#contact">Discuss customization</a><a class="text-link" href="#capabilities">Our capabilities →</a></div></div><div class="hero-visual"><img src="/assets/hero/custom-development.jpg" alt="Custom car trunk organizer"><div class="floating-note"><b>OEM / ODM development</b><span>Product and packaging options</span></div></div></article><article class="hero-slide"><div class="hero-copy"><p class="eyebrow">03 · DELIVERY & SUPPORT</p><h1>On-time delivery.<br>Support that lasts.</h1><p class="hero-lede">Clear production updates, quality checkpoints and responsive after-sales support keep every order moving with confidence.</p><div class="hero-actions"><a class="button dark" href="#contact">Talk to our team</a><a class="text-link" href="#process">How we work →</a></div></div><div class="hero-visual"><img src="/assets/hero/delivery-support.jpg" alt="Vehicle tool bag"><div class="floating-note"><b>Reliable order follow-through</b><span>After-sales response</span></div></div></article></div><div class="slider-controls"><div class="slider-dots"><button class="active" aria-label="Show fast response slide">01</button><button aria-label="Show custom development slide">02</button><button aria-label="Show delivery and support slide">03</button></div><div class="slider-arrows"><button class="slider-prev" aria-label="Previous slide">←</button><button class="slider-next" aria-label="Next slide">→</button></div></div></section><section class="hero-stats"><div><strong>3</strong><span>focused automotive product lines</span></div><div><strong>85</strong><span>production-ready catalog products</span></div><div><strong>OEM</strong><span>materials, colors, logo and packaging</span></div></section>
<section class="category-section" id="products"><div class="section-head"><div><p class="eyebrow">WHAT WE MAKE</p><h2>Products that earn<br>their place in the car.</h2></div><p>Purposeful materials, practical construction and flexible customization across a focused automotive range.</p></div><div class="category-grid">${categoryTiles}</div></section>
<section class="manifesto"><p class="eyebrow light">A PRACTICAL SUPPLY PARTNER</p><p>Start smaller. Adapt faster. Reorder with confidence.</p><div class="manifesto-grid"><span>Lower-risk trial orders</span><span>Rapid sample development</span><span>Flexible private labeling</span><span>Responsive repeat production</span></div></section>
<section class="capabilities" id="capabilities"><div class="capability-image"><img src="${data.categories[0].products[4]?.image || data.categories[0].products[0].image}" alt="Automotive accessory detail" loading="lazy"></div><div><p class="eyebrow">ABOUT CHAMPO</p><h2>A responsive manufacturing partner for growing programs.</h2><p class="company-copy">We focus on fabric-based automotive accessories and work closely with customers who need practical quantities, quick product iterations and reliable replenishment. Instead of forcing every project into a fixed catalog, we adapt materials, construction, colors, branding and packaging to suit the target market.</p><div class="accordion"><details open><summary>01 · Small-order flexibility</summary><p>Lower-risk trial orders help buyers test new products and markets before scaling.</p></details><details><summary>02 · Fast response & replenishment</summary><p>Direct communication and focused product lines support quicker sampling and repeat orders.</p></details><details><summary>03 · Product customization</summary><p>Material, dimensions, functional details and colorways can be developed around your brief.</p></details><details><summary>04 · Branding & packaging</summary><p>Custom logo, labels, inserts and retail-ready packaging for private-label programs.</p></details></div></div></section>
<section class="experience" id="experience"><div class="section-head"><div><p class="eyebrow">PROGRAM EXPERIENCE</p><h2>Built for different<br>routes to market.</h2></div><p>Working through established export partners, we have supported product programs supplied into major North American retail channels.</p></div><div class="case-grid"><article><span>01</span><p>Warehouse retail</p><h3>Pet travel protection program</h3><p>Material adaptation, reinforced construction, retail packaging and volume production for a North American warehouse retail channel.</p></article><article><span>02</span><p>Automotive retail</p><h3>Vehicle tool storage program</h3><p>Private-label tool bags developed around assortment, packing and repeat-delivery requirements for an automotive retail channel.</p></article><article><span>03</span><p>Import & distribution</p><h3>Car organization program</h3><p>Flexible trunk organizer development for importers testing multiple styles, colors and market price points.</p></article></div><div class="capacity-panel"><div><p class="eyebrow light">DAILY PRODUCTION CAPACITY</p><h2>From trial orders to repeat volume.</h2><p>Focused production lines allow us to respond to different order sizes and replenishment schedules.</p></div><dl><div><dt>Car organizers</dt><dd><strong>1,000</strong><span>pcs / day</span></dd></div><div><dt>Pet protection</dt><dd><strong>1,000</strong><span>sets / day</span></dd></div><div><dt>Vehicle tool bags</dt><dd><strong>3,000</strong><span>pcs / day</span></dd></div></dl></div><p class="disclosure">Program descriptions are anonymized. Products were supplied through export partners; no direct commercial relationship with downstream retailers is implied.</p></section>
<section class="process" id="process"><div class="section-head"><div><p class="eyebrow">HOW WE WORK</p><h2>A clear route from<br>idea to delivery.</h2></div></div><ol><li><span>01</span><b>Share the brief</b><p>Product, target price, quantity and market.</p></li><li><span>02</span><b>Confirm the solution</b><p>Materials, details, sample and quotation.</p></li><li><span>03</span><b>Make & inspect</b><p>Production with quality checkpoints.</p></li><li><span>04</span><b>Pack & ship</b><p>Final inspection and export coordination.</p></li></ol></section>${inquiry()}`;
await fs.writeFile(path.join(out,"index.html"),layout({title:"CHAMPO | Automotive Accessories Manufacturer",description:"OEM and ODM automotive organizers, pet seat covers, cargo liners and car protection products.",body:homeBody,canonical:"/"}));

const legacySourceSlug={"Trunk Organizers":"storage-box","Seat Organizers":"seat-hanging-bag","Pet Seat Covers":"pet-seat-cover","Cargo Liners":"trunk-mat","Tool Bags":"tool-kit"};
for(const c of data.categories){
  const dir=path.join(out,"products",c.slug); await fs.mkdir(dir,{recursive:true});
  const body=`<section class="page-hero"><p class="eyebrow">PRODUCT COLLECTION</p><h1>${esc(c.name)}</h1><p>${esc(c.intro)}</p><span>${c.products.length} products</span></section><section class="catalog-grid">${c.products.map(p=>card(c,p)).join("")}</section>${inquiry(c.name)}`;
  await fs.writeFile(path.join(dir,"index.html"),layout({title:`${c.name} | CHAMPO`,description:c.intro,body,canonical:`/products/${c.slug}/`}));
  for(const p of c.products){
    const pdir=path.join(dir,p.sku.toLowerCase()); await fs.mkdir(pdir,{recursive:true});
    const facts=[["Item no.",p.sku],["Size",p.dimension],["Packing",p.packing],["Net weight",p.weight],["MOQ",p.moq?`${p.moq} pcs`:"Ask us"],["Colors",p.colors.join(", ")||"Custom options"]].filter(x=>x[1]);
    const gallery=[p.image,...p.gallery].slice(0,4).map((img,i)=>`<img src="${img}" alt="${esc(p.name)}${i?` detail ${i}`:""}" ${i?"loading=\"lazy\"":""}>`).join("");
    const schema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"Product",name:p.name,sku:p.sku,image:[url(p.image)],brand:{"@type":"Brand",name:"CHAMPO"},description:p.description||c.intro})}</script>`;
    const pbody=`<nav class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/products/${c.slug}/">${esc(c.name)}</a><span>/</span><b>${esc(p.sku)}</b></nav><section class="product-detail"><div class="gallery">${gallery}</div><div class="product-info"><p class="eyebrow">${esc(c.name)}</p><h1>${esc(p.sku)}</h1><p class="product-lede">${esc(p.description||c.intro)}</p><dl>${facts.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl><a class="button dark wide" href="#contact">Request quote</a><p class="microcopy">Logo, color and packaging customization available.</p></div></section>${inquiry(`${p.sku} / ${c.name}`)}`;
    await fs.writeFile(path.join(pdir,"index.html"),layout({title:`${p.sku} ${c.name.replace(/s$/,'')} | CHAMPO`,description:p.description||c.intro,body:pbody,canonical:productUrl(c,p),schema}));
    const oldSlug=legacySourceSlug[p.sourceCategory];
    if(oldSlug){const oldDir=path.join(out,"products",oldSlug,p.sku.toLowerCase());await fs.mkdir(oldDir,{recursive:true});const target=productUrl(c,p);await fs.writeFile(path.join(oldDir,"index.html"),`<!doctype html><meta charset="utf-8"><link rel="canonical" href="${url(target)}"><meta http-equiv="refresh" content="0;url=${target}"><title>Moved | CHAMPO</title><a href="${target}">View this product</a>`)}
  }
}
const legacyCategories={"storage-box":"car-organizers","seat-hanging-bag":"car-organizers","pet-seat-cover":"pet-car-protection","trunk-mat":"pet-car-protection","tool-kit":"vehicle-tool-kits"};
for(const [oldSlug,newSlug] of Object.entries(legacyCategories)){const d=path.join(out,"products",oldSlug);await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"index.html"),`<!doctype html><meta charset="utf-8"><link rel="canonical" href="${url(`/products/${newSlug}/`)}"><meta http-equiv="refresh" content="0;url=/products/${newSlug}/"><title>Moved | CHAMPO</title><a href="/products/${newSlug}/">View the current collection</a>`)}
const allProducts=data.categories.flatMap(c=>c.products.map(p=>({sku:p.sku,name:p.name,category:c.name,url:productUrl(c,p),image:p.image}))); 
await fs.writeFile(path.join(out,"products.json"),JSON.stringify(allProducts,null,2));
await fs.writeFile(path.join(out,"robots.txt"),`User-agent: *\nAllow: /\nSitemap: ${url('/sitemap.xml')}\n`);
const paths=["/",...data.categories.map(c=>`/products/${c.slug}/`),...data.categories.flatMap(c=>c.products.map(p=>productUrl(c,p)))];
await fs.writeFile(path.join(out,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${url(p)}</loc></url>`).join("")}</urlset>`);
console.log(`Built ${paths.length} pages in ${out}`);
